sudo: false
language: node_js
node_js:
  - stable
cache:
  npm: true
  directories:
    - node_modules

branches:
  only:
    - source # build source branch only

before_install:
  - export TZ='Asia/Shanghai'
  - git config --global user.name ${USER_NAME}
  - git config --global user.email ${USER_EMAIL}
  - npm install -g hexo-cli
  - npm install
  # 字数统计，时长统计需要工具
  - npm install hexo-wordcount --save
  # 中英文之间自动增加空格插件
  - npm install hexo-pangu-spacing --save
  - npm install hexo-deployer-git --save
  - git config --global user.name ${USER_NAME}
  - git config --global user.email ${USER_EMAIL}
install:
  - npm install
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: source
  local_dir: public
  target_branch: master