sudo: false
language: node_js
node_js:
  - stable
cache:
  npm: true
  directories:
    - node_modules

branches:
  only:
    - blog # build source branch only

before_install:
  - export TZ='Asia/Shanghai'
  - git config --global user.name ${USER_NAME}
  - git config --global user.email ${USER_EMAIL}
  - npm install -g hexo-cli
  - npm install
  # 字数统计, 时长统计需要工具
  - npm install hexo-symbols-count-time --save
  # 中英文之间自动增加空格插件
  - npm install hexo-pangu-spacing --save
  - git config --global user.name ${USER_NAME}
  - git config --global user.email ${USER_EMAIL}
install:
  - npm install
script:
  - hexo clean
  - hexo generate
after_success:
  # 获取 master 分支内容
  - git clone https://${GH_URL} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cp -rf ../public/* ./
  # 必要配置文件
  - cp -rf ../README.md ./
  - git add .
  # 提交记录包含时间, 跟上面更改时区配合
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  # 推送到主分支
  - git push --force --quiet "https://${GH_TOKEN}@${GH_URL}" master:master